const DIFFICULTY = 2;
const MINING_REWARD = 50;
const COINBASE_TX_ID = 'coinbase';
const MAX_MEMPOOL_SIZE = 500;
const DIFFICULTY_ADJUSTMENT_INTERVAL = 5;
const TARGET_BLOCK_TIME_MS = 1000;
const DEFAULT_PORT = 3001;
const DEFAULT_P2P_PORT = 6001;

module.exports = { DIFFICULTY, MINING_REWARD, COINBASE_TX_ID, MAX_MEMPOOL_SIZE, DIFFICULTY_ADJUSTMENT_INTERVAL, TARGET_BLOCK_TIME_MS, DEFAULT_PORT, DEFAULT_P2P_PORT };
